name: Python package

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: ci
    strategy:
      fail-fast: false
      matrix:
#       python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Rasa and dependencies
        run: poetry install
      - name: Verify that Rasa CLI is runnable
        env:
          RASA_PRO_LICENSE: aaaaa.bbbbb.ccccc
        continue-on-error: true
        run: |
          $(poetry run rasa --version; exit 0) >> $RASA_RUN_STDOUT
      - name: Actual versus expected
        run: |
          echo $RASA_RUN_STDOUT
          [[ "$RASA_RUN_STDOUT" =~ "Failed to validate Rasa Pro license" ]]
