name: Python package

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: ci
    strategy:
      fail-fast: false
      matrix:
#       python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/setup-and-cache-python-poetry
      - name: Set up Python, poetry, and dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Save the output of 'rasa --version'
        continue-on-error: true
        env:
          RASA_PRO_LICENSE: aaaaa.bbbbb.ccccc
        run: |
          TMP="$(poetry run rasa --version 2>&1)"
          echo "RASA_RUN_STDOUT='$TMP'" >> $GITHUB_ENV
      - name: Compare actual output to known good
        run: |
          [[ "$RASA_RUN_STDOUT" =~ "Failed to validate Rasa Pro license" ]]
