name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Rasa and dependencies
        run: poetry install
      - name: Verify that Rasa CLI is runnable
        env:
          RASA_LICENSE_KEY: aaaaaaaaaaaa
        run: poetry run rasa --version
